In [2]:
import numpy as np

# np.sort

In [22]:
a=np.array([2,3,55,1,0,6]) # 1D in ascending order
print(np.sort(a))

[ 0  1  2  3  6 55]


In [11]:
a=np.array([2,3,55,1,0,6]) # 1D in descending order
print(np.sort(a)[::-1])

[55  6  3  2  1  0]


In [20]:
a=np.random.randint(10,30,12).reshape(3,4)
print(a,"\n")
print(np.sort(a),"\n") # row wise sord
print(np.sort(a,axis=0)) # column wise sort 

[[27 25 11 11]
 [27 15 20 14]
 [27 17 27 20]] 

[[11 11 25 27]
 [14 15 20 27]
 [17 20 27 27]] 

[[27 15 11 11]
 [27 17 20 14]
 [27 25 27 20]]


# np.append

In [24]:
a

array([ 2,  3, 55,  1,  0,  6])

In [27]:
print(np.append(a,12))
print(np.append(a,[111,222,333]))

[ 2  3 55  1  0  6 12]
[  2   3  55   1   0   6 111 222 333]


# np.concatenate

In [33]:
a=np.random.randint(10,30,6)
b=np.random.randint(10,30,6)
print(a)
print()
print(b)
print()
print(np.concatenate((a,b)))  # 

[16 25 27 16 14 29]

[21 10 24 25 26 14]

[16 25 27 16 14 29 21 10 24 25 26 14]


In [37]:
a=np.random.randint(10,30,6).reshape(2,3)
b=np.random.randint(10,30,6).reshape(2,3)
print(a)
print()
print(b)
print()
print(np.concatenate((a,b)))  
print()
print(np.concatenate((a,b),axis=1))

[[25 21 20]
 [16 10 14]]

[[28 23 16]
 [14 18 27]]

[[25 21 20]
 [16 10 14]
 [28 23 16]
 [14 18 27]]

[[25 21 20 28 23 16]
 [16 10 14 14 18 27]]


# np.unique

In [38]:
a=np.array([1,2,3,44,5,6,3,1,44])
print(np.unique(a))

[ 1  2  3  5  6 44]


# np.expand_dims

In [9]:
a=np.arange(12,24)
print(np.expand_dims(a,axis=0))

[[12 13 14 15 16 17 18 19 20 21 22 23]]


# np.where

In [23]:
# np.where with 1 parameter or arguments
a=np.random.randint(10,50,8)
print(a)
print(np.where(a>25))

[13 15 38 21 17 24 32 48]
(array([2, 6, 7]),)


In [28]:
# np.where with 3 parameter or arguments

b=np.random.randint(10,50,8)
print(b)
print(np.where(b>25,b,0))

[14 47 31 30 32 14 33 22]
[ 0 47 31 30 32  0 33  0]


In [29]:
# np.where with 3 parameter or arguments

b=np.random.randint(10,50,8)
print(b)
print(np.where(b>25,"big","small"))

[36 30 44 22 32 46 22 31]
['big' 'big' 'big' 'small' 'big' 'big' 'small' 'big']


In [31]:
# np.where with 3 parameter or arguments

b=np.arange(20)
print(b)
print(np.where(b%2==0,"even","odd"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
['even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even'
 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd']


# np.argmax

In [33]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
print(np.argmax(b))

19


# np.argmin

In [35]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
print(np.argmin(b))

0


# np.cumsum

In [53]:
a=np.arange(11)
print(np.cumsum(a))

[ 0  1  3  6 10 15 21 28 36 45 55]


In [61]:
d2 = np.arange(12).reshape(4,3)
print(d2,"\n")
print(np.cumsum(d2,axis=1))  # 1 is for rows wise operation
print()
print(np.cumsum(d2,axis=0))  # 0 is for columns wise operation

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]
 [ 9 19 30]]

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]
 [18 22 26]]


# np.cumprod

In [68]:
a = np.arange(1,11)

In [69]:
print(np.cumprod(a))

[      1       2       6      24     120     720    5040   40320  362880
 3628800]


# np.percentile

In [78]:
a=np.random.randint(30,100,30)
print(a)
print()
print(np.percentile(a,25)) #25th 
print()
print(np.percentile(a,50))   #50th   median
print()
print(np.percentile(a,75))    #75th 

[46 77 81 51 32 64 43 93 44 49 41 74 49 34 89 73 36 91 58 30 73 92 91 45
 67 88 83 61 89 93]

45.25

65.5

86.75


In [76]:
print(np.median(a))

72.0


In [87]:
# find max number using percentile
print("max number from the array")
print(np.percentile(a,100))

max number from the array
93.0


In [86]:
# find min number using percentile
print("min number from the array")
print(np.percentile(a,0))

min number from the array
30.0


# np.histogram

In [117]:
a=np.random.randint(1,100,40)
print(a,"\n")
print(np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100]))
print()
print(np.where(a>=90,a,0))

[95 73 63  2 84 80 84 51 45 94  8 20 55 72 50 82 16 86 46 48  6 37 40 78
 90 20  9 45  8 52 50 34 12 20  4  3 41 60 36 28] 

(array([7, 2, 4, 3, 6, 5, 2, 3, 5, 3]), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

[95  0  0  0  0  0  0  0  0 94  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 90  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]


# np.corrcoef

In [118]:
salary=np.array([200,400,250,350,600])
experience=np.array([1,3,2,4,5])
print(np.corrcoef(salary,experience))

[[1.         0.91381155]
 [0.91381155 1.        ]]


# np.isin

In [121]:
a=np.arange(10)
print(np.isin(a,2))

[False False  True False False False False False False False]


In [122]:
a=np.arange(10)
print(np.isin(a,[2,5,9]))

[False False  True False False  True False False False  True]


In [124]:
a=np.arange(10)
print(a[np.isin(a,[2,5,9])])

[2 5 9]


In [125]:
# opposite of np.isin not in check
print(a[np.isin(a,[2,5,9],invert=True)])

[0 1 3 4 6 7 8]


# flip

In [126]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
print(np.flip(a))

[9 8 7 6 5 4 3 2 1 0]


# np.put

In [136]:
a=np.arange(10)

In [137]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
np.put(a,[0,1],[22,11])

In [142]:
print(a)

[22 11  2  3  4  5  6  7  8  9]


# np.delete

In [144]:
a

array([22, 11,  2,  3,  4,  5,  6,  7,  8,  9])

In [145]:
print(np.delete(a,0))

[11  2  3  4  5  6  7  8  9]


In [146]:
print(np.delete(a,[3,6]))

[22 11  2  4  5  7  8  9]


# set function

In [148]:
#np.union1d
m=np.array([1,2,4,3])
n=np.array([1,6,7,3])
print(np.union1d(m,n))

[1 2 3 4 6 7]


In [149]:
#np.intersect1d
m=np.array([1,2,4,3])
n=np.array([1,6,7,3])
print(np.intersect1d(m,n))

[1 3]


In [151]:
#np.setdiff1d
m=np.array([1,2,4,3])
n=np.array([1,6,7,3])
print(np.setdiff1d(m,n))

[2 4]


In [152]:
#np.setxor1d
m=np.array([1,2,4,3])
n=np.array([1,6,7,3])
print(np.setxor1d(m,n))

[2 4 6 7]


In [156]:
#np.in1d
m=np.array([1,2,4,3])
n=np.array([1,6,7,3])
print(np.in1d(m,4))

[False False  True False]


C:\Users\Balaji Jadhav\AppData\Local\Temp\ipykernel_19136\2121200630.py:4: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(m,4))


# np.clip

In [158]:
a=np.array([3,7,9,11,221,38])
print(np.clip(a,a_min=8,a_max=30))

[ 8  8  9 11 30 30]
