# Creating numpy arrays

In [2]:
# np.array
import numpy as np
a= np.array([1,2,3])  # 1D array
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2D array
b=np.array([[1,2,3],[4,5,6]])  
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
# 3D array
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
# dtype
d=np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


# create array with arange function

In [7]:
# arange function work just like range function in python
a= np.arange(1,11)
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [9]:
b = np.arange(1,11,2)
print(b)

[1 3 5 7 9]


# reshape function 

In [12]:
# reshape function
a=np.arange(1,13).reshape(3,4)  # 3 rows and 4 columns   2D array
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
a=np.arange(24).reshape(2,3,4)    # 2 block 3 rows 4 columns 3D array
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [20]:
a=np.arange(1,17)  # 3 rows and 4 columns   2D array
b=a.reshape(4,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [21]:
b=np.array([[1,2,3],[4,5,6]]).reshape(-1)
print(b)

[1 2 3 4 5 6]


# ones

In [26]:
# ones
arr=np.ones((5))  #1D
print(arr)
print(type(arr))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [27]:
arr=np.ones((2,4)) #2D
print(arr)
print(type(arr))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [29]:
# ones
arr=np.ones((2,3,4))  #3D
print(arr)
print(type(arr))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<class 'numpy.ndarray'>


# zeros

In [31]:
# zeros
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# linspace

In [45]:
# reshape
arr= np.linspace(1,10,15)
print(arr)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [46]:
arr= np.linspace(1,2,25).reshape(5,5)
print(arr)

[[1.         1.04166667 1.08333333 1.125      1.16666667]
 [1.20833333 1.25       1.29166667 1.33333333 1.375     ]
 [1.41666667 1.45833333 1.5        1.54166667 1.58333333]
 [1.625      1.66666667 1.70833333 1.75       1.79166667]
 [1.83333333 1.875      1.91666667 1.95833333 2.        ]]


In [54]:
arr=np.linspace(10,15,5)
print(arr)

[10.   11.25 12.5  13.75 15.  ]


In [52]:
arr=np.linspace(-10,10,8)
print(arr)

[-10.          -7.14285714  -4.28571429  -1.42857143   1.42857143
   4.28571429   7.14285714  10.        ]


In [53]:
arr=np.linspace(-10,10,8,dtype=int)
print(arr)

[-10  -8  -5  -2   1   4   7  10]


# identity

In [47]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Attributes

In [65]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(16,dtype=float).reshape(4,4)
a3=np.arange(18).reshape(2,3,3)
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [61]:
# ndim

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [62]:
# shape

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(4, 4)
(2, 3, 3)


In [63]:
# size

print(a1.size)
print(a2.size)
print(a3.size)

10
16
18


In [66]:
# itemsize

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [67]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


# Changing datatype

In [77]:
a=np.array([1,2,3])
b=a.astype(np.int32)
c=b.astype(bool)
print(a)
print(a.dtype)
print(b.dtype)
print(c)
print(c.dtype)

[1 2 3]
int64
int32
[ True  True  True]
bool


# Array operation

In [79]:
a1=np.arange(4).reshape(2,2)
a2=np.arange(12,16).reshape(2,2)
print(a1)
print()
print(a2)

[[0 1]
 [2 3]]

[[12 13]
 [14 15]]


In [80]:
#scaler operation
# arithmatic
print(a1+2)
print()
print(a2*3)
print()
print(a1-23)
print()

[[2 3]
 [4 5]]

[[36 39]
 [42 45]]

[[-23 -22]
 [-21 -20]]



In [83]:
# relational or comparison
print(a1>2)
print()
print(a2==12)
print()
print(a1!=5)

[[False False]
 [False  True]]

[[ True False]
 [False False]]

[[ True  True]
 [ True  True]]


In [88]:
# Vector operation
print(a1+a2)
print()
print(a2*a1)
print()
print(a1-a2)

[[12 14]
 [16 18]]

[[ 0 13]
 [28 45]]

[[-12 -12]
 [-12 -12]]


# Array Function

In [102]:
a1=np.random.random((3,3))
print(a1)
a2=np.round(a1*100)
print(a2)

[[0.34031831 0.8506059  0.15143542]
 [0.46688217 0.12581103 0.41874343]
 [0.11777973 0.64279902 0.49991691]]
[[34. 85. 15.]
 [47. 13. 42.]
 [12. 64. 50.]]


# max,min,sum,prod

In [103]:
print(np.max(a2))
print(np.min(a2))
print(np.sum(a2))
print(np.prod(a2))

85.0
12.0
362.0
42717991680000.0


In [109]:
# row wise max,min,sum,prod
# 0 -> column and 1 -> row
print(np.max(a2,axis=1))
print(np.min(a2,axis=1))
print(np.sum(a2,axis=1))
print(np.prod(a2,axis=1))

[85. 47. 64.]
[15. 13. 12.]
[134. 102. 126.]
[43350. 25662. 38400.]


In [110]:
# column wise max,min,sum,prod
# 0 -> column and 1 -> row
print(np.max(a2,axis=0))
print(np.min(a2,axis=0))
print(np.sum(a2,axis=0))
print(np.prod(a2,axis=0))

[47. 85. 50.]
[12. 13. 15.]
[ 93. 162. 107.]
[19176. 70720. 31500.]


# Statistical Function

# mean,median,std,var

In [5]:
a1=np.random.random((3,3))
print(a1)
print()
a2=np.round(a1*100)
print(a2)
print()
print(np.mean(a2))
print(np.median(a2))
print(np.std(a2))
print(np.var(a2))

[[0.53386744 0.95053137 0.28418845]
 [0.77945716 0.93754205 0.90129003]
 [0.10681575 0.81341917 0.50954583]]

[[53. 95. 28.]
 [78. 94. 90.]
 [11. 81. 51.]]

64.55555555555556
78.0
28.70195932572901
823.8024691358025


In [120]:
# trigonomentry function
print(np.sin(a1))
print()
print(np.cos(a1))
print()
print(np.tan(a1))

[[0.52716089 0.61566209 0.52516577]
 [0.52464453 0.52576145 0.20612042]
 [0.3886607  0.41675226 0.69112242]]

[[0.84976549 0.78801027 0.85099995]
 [0.8513214  0.85063206 0.97852663]
 [0.92138095 0.90902011 0.72273771]]

[[0.62036044 0.78128689 0.61711609]
 [0.61627081 0.61808327 0.21064365]
 [0.42182411 0.4584632  0.95625621]]


# dot product

In [7]:
a1=np.arange(4).reshape(2,2)
a2=np.arange(12,16).reshape(2,2)
print(a1)
print()
print(a2)
print()
print(np.dot(a1,a2))

[[0 1]
 [2 3]]

[[12 13]
 [14 15]]

[[14 15]
 [66 71]]


# round / floor / ceil

In [66]:
#round
a=np.random.random((3,3))
print(a)
print()
print(np.round(a)*100)

[[0.40227157 0.91333138 0.29484202]
 [0.71722513 0.08403554 0.19433917]
 [0.88788529 0.14927763 0.47008708]]

[[  0. 100.   0.]
 [100.   0.   0.]
 [100.   0.   0.]]


In [69]:
a = np.array([1.9, 2.1, -1.5])
print(np.floor(a))

[ 1.  2. -2.]


In [67]:
#floor
a = np.array([1.9, 2.1, -1.5])
print(np.floor(a))

[ 1.  2. -2.]


In [68]:
#ceil
a = np.array([1.2, 2.8, -1.5])
print(np.ceil(a))

[ 2.  3. -1.]


# Indexing and Slicing

In [86]:
# Indexing
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)

print()
print("1D array")
print(a1[4])
print(a1[-1])

print()
print("2D array")
print(a2[1,2])

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

1D array
4
9

2D array
6


In [82]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [83]:
print(a3[1,1,0])

6


In [84]:
print(a3[0,1,1])

3


In [85]:
print(a3[0,0,0])

0


In [87]:
#slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
a1[3:8]

array([3, 4, 5, 6, 7])

In [91]:
a1[1:5]

array([1, 2, 3, 4])

In [92]:
a1[1:6:2]

array([1, 3, 5])

In [100]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a2[0,:]

array([0, 1, 2, 3])

In [94]:
a2[:,3]

array([ 3,  7, 11])

In [95]:
a2[1:3,3]

array([ 7, 11])

In [98]:
a2[2,1:4]

array([ 9, 10, 11])

In [99]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [101]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
a2[1,::3]

array([4, 7])

In [131]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [133]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [148]:
a3[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [149]:
a3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [153]:
a3[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [141]:
a3[0,1,:]

array([3, 4, 5])

In [147]:
a3[1,:,1]

array([10, 13, 16])

In [150]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [154]:
a3[0:3:2,0,::2]

array([[ 0,  2],
       [18, 20]])

# iteration

In [161]:
print(a1)
for i in a1:
    print(i,end=" ")

[0 1 2 3 4 5 6 7 8 9]
0 1 2 3 4 5 6 7 8 9 

In [164]:
print(a2)
print()
print()
for i in a2:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [165]:
print(a3)
print()
print()
for i in a3:
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [167]:
for i in np.nditer(a3):
    print(i,end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

# Transpose

In [182]:
print(a2)
print("\n")
print(np.transpose(a2))  # or print(a2.T) both work same
print()
print(a2.T)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# ravel

In [187]:
print(a3.ravel())

print()
print(a2.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Stacking

In [194]:
# horizontal stacking
a1=np.arange(4).reshape(2,2)
a2=np.arange(5,9).reshape(2,2)
print(a1)
print()
print(a2)
print("\n")
print(np.hstack((a1,a2)))

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


[[0 1 5 6]
 [2 3 7 8]]


In [195]:
# vertical stacking
a1=np.arange(4).reshape(2,2)
a2=np.arange(5,9).reshape(2,2)
print(a1)
print()
print(a2)
print("\n")
print(np.vstack((a1,a2)))

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


[[0 1]
 [2 3]
 [5 6]
 [7 8]]


# splitting

In [206]:
a3=np.arange(12).reshape(3,4)

#horizontal splitting

print(a3)
print()
print(np.hsplit(a3,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [209]:
a4=np.arange(12,24).reshape(3,4)

#vertical splitting

print(a4)
print()
print(np.vsplit(a4,3))

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
